[theme]
primaryColor = "#0077B3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#003366"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
